theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: Vibhuti

description: Airbnb New User Bookings

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
